import { CategoryContent } from "@/entities/categoryContent";
import { Menu } from "@/entities/menu";
import { Product } from "@/entities/product";

export const categoryData: Array<CategoryContent> = [
  {
    category_name: "Category 1",
    category_id: "1",
    items: [
      {
        id_menu: "5",
        name: "Menu 1",
        description: "oui descr",
        menu_image_url: "path/to/file.png",
        price: 30.25,
        category: "kebab",
        menu_ordered_categories: "jcp frr",
        products: [
          {
            id_product: "1",
            name: "Produit 1",
            price: 21.35,
            description: "produit 1 descr",
            product_image_url: "path/to/file3.png",
            category: "pizza",
            id_restaurant: "11111111111111111",
          },
          {
            id_product: "2",
            name: "Produit 2",
            price: 5.69,
            description: "produit 2 descr",
            product_image_url: "path/to/file4.png",
            category: "pizza",
            id_restaurant: "22222222222222222",
          },
        ],
      },
      {
        id_menu: "6",
        name: "Menu 2",
        description: "non descr",
        menu_image_url: "path/to/file2.png",
        price: 54.21,
        category: "burger",
        menu_ordered_categories: "jctp frr",
        products: [
          {
            id_product: "3",
            name: "Produit 3",
            price: 8.52,
            description: "produit 3 descr",
            product_image_url: "path/to/file5.png",
            category: "salade",
            id_restaurant: "22222222222222222",
          },
          {
            id_product: "4",
            name: "Produit 4",
            price: 6.23,
            description: "produit 4 descr",
            product_image_url: "path/to/file6.png",
            category: "salade",
            id_restaurant: "11111111111111111111",
          },
        ],
      },
      {
        id_product: "1",
        name: "Produit 1",
        price: 21.35,
        description: "produit 1 descr",
        product_image_url: "path/to/file3.png",
        category: "pizza",
        id_restaurant: "11111111111111111",
      },
    ],
  },
  {
    category_name: "Category 2",
    category_id: "2",
    items: [
      {
        id_product: "2",
        name: "Produit 2",
        price: 5.69,
        description: "produit 2 descr",
        product_image_url: "path/to/file4.png",
        category: "pizza",
        id_restaurant: "22222222222222222",
      },
      {
        id_menu: "6",
        name: "Menu 2",
        description: "non descr",
        menu_image_url: "path/to/file2.png",
        price: 54.21,
        category: "burger",
        menu_ordered_categories: "jctp frr",
        products: [
          {
            id_product: "3",
            name: "Produit 3",
            price: 8.52,
            description: "produit 3 descr",
            product_image_url: "path/to/file5.png",
            category: "salade",
            id_restaurant: "22222222222222222",
          },
          {
            id_product: "4",
            name: "Produit 4",
            price: 6.23,
            description: "produit 4 descr",
            product_image_url: "path/to/file6.png",
            category: "salade",
            id_restaurant: "11111111111111111111",
          },
        ],
      },
    ],
  },
  {
    category_name: "Category 3",
    category_id: "3",
    items: [
      {
        id_product: "1",
        name: "Produit 1",
        price: 21.35,
        description: "produit 1 descr",
        product_image_url: "path/to/file3.png",
        category: "pizza",
        id_restaurant: "11111111111111111",
      },
      {
        id_menu: "7",
        name: "Menu 3",
        description: "menu 3 descr",
        menu_image_url: "path/to/file10.png",
        price: 12.41,
        category: "tacos",
        menu_ordered_categories: "jctp frr",
        products: [
          {
            id_product: "3",
            name: "Produit 3",
            price: 8.52,
            description: "produit 3 descr",
            product_image_url: "path/to/file5.png",
            category: "salade",
            id_restaurant: "22222222222222222",
          },
          {
            id_product: "4",
            name: "Produit 4",
            price: 6.23,
            description: "produit 4 descr",
            product_image_url: "path/to/file6.png",
            category: "salade",
            id_restaurant: "11111111111111111111",
          },
        ],
      },
    ],
  },
];

export const itemsData: Array<Menu | Product> = [
  {
    id_product: "1",
    name: "Produit 1",
    price: 21.35,
    description: "produit 1 descr",
    product_image_url: "path/to/file3.png",
    category: "pizza",
    id_restaurant: "11111111111111111",
  },
  {
    id_product: "2",
    name: "Produit 2",
    price: 5.69,
    description: "produit 2 descr",
    product_image_url: "path/to/file4.png",
    category: "pizza",
    id_restaurant: "22222222222222222",
  },
  {
    id_product: "3",
    name: "Produit 3",
    price: 8.52,
    description: "produit 3 descr",
    product_image_url: "path/to/file5.png",
    category: "salade",
    id_restaurant: "22222222222222222",
  },
  {
    id_product: "4",
    name: "Produit 4",
    price: 6.23,
    description: "produit 4 descr",
    product_image_url: "path/to/file6.png",
    category: "salade",
    id_restaurant: "11111111111111111111",
  },
  {
    id_menu: "5",
    name: "Menu 1",
    description: "oui descr",
    menu_image_url: "path/to/file.png",
    price: 30.25,
    category: "kebab",
    menu_ordered_categories: "jcp frr",
    products: [
      {
        id_product: "1",
        name: "Produit 1",
        price: 21.35,
        description: "produit 1 descr",
        product_image_url: "path/to/file3.png",
        category: "pizza",
        id_restaurant: "11111111111111111",
      },
      {
        id_product: "2",
        name: "Produit 2",
        price: 5.69,
        description: "produit 2 descr",
        product_image_url: "path/to/file4.png",
        category: "pizza",
        id_restaurant: "22222222222222222",
      },
    ],
  },
  {
    id_menu: "6",
    name: "Menu 2",
    description: "non descr",
    menu_image_url: "path/to/file2.png",
    price: 54.21,
    category: "burger",
    menu_ordered_categories: "jctp frr",
    products: [
      {
        id_product: "3",
        name: "Produit 3",
        price: 8.52,
        description: "produit 3 descr",
        product_image_url: "path/to/file5.png",
        category: "salade",
        id_restaurant: "22222222222222222",
      },
      {
        id_product: "4",
        name: "Produit 4",
        price: 6.23,
        description: "produit 4 descr",
        product_image_url: "path/to/file6.png",
        category: "salade",
        id_restaurant: "11111111111111111111",
      },
    ],
  },
  {
    id_menu: "7",
    name: "Menu 3",
    description: "menu 3 descr",
    menu_image_url: "path/to/file10.png",
    price: 12.41,
    category: "tacos",
    menu_ordered_categories: "jctp frr",
    products: [
      {
        id_product: "3",
        name: "Produit 3",
        price: 8.52,
        description: "produit 3 descr",
        product_image_url: "path/to/file5.png",
        category: "salade",
        id_restaurant: "22222222222222222",
      },
      {
        id_product: "4",
        name: "Produit 4",
        price: 6.23,
        description: "produit 4 descr",
        product_image_url: "path/to/file6.png",
        category: "salade",
        id_restaurant: "11111111111111111111",
      },
    ],
  },
];
