/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/_user'
import { Route as RestaurantImport } from './routes/_restaurant'
import { Route as LoginImport } from './routes/_login'
import { Route as DeliveryImport } from './routes/_delivery'
import { Route as IndexImport } from './routes/index'
import { Route as ComponentsIndexImport } from './routes/components/index'
import { Route as UserUserImport } from './routes/_user/user'
import { Route as RestaurateurRestaurateurImport } from './routes/_restaurateur/restaurateur'
import { Route as RestaurateurCreateEditProductImport } from './routes/_restaurateur/create-edit-product'
import { Route as LoginSignupImport } from './routes/_login/signup'
import { Route as LoginLoginImport } from './routes/_login/login'
import { Route as DeliveryDeliveryImport } from './routes/_delivery/delivery'
import { Route as DeliveryDeliveriesHistoryImport } from './routes/_delivery/deliveries-history'
import { Route as DeliveryDeliveriesImport } from './routes/_delivery/deliveries'
import { Route as UserRestaurantIdImport } from './routes/_user/restaurant.$id'

// Create/Update Routes

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantRoute = RestaurantImport.update({
  id: '/_restaurant',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/_login',
  getParentRoute: () => rootRoute,
} as any)

const DeliveryRoute = DeliveryImport.update({
  id: '/_delivery',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsIndexRoute = ComponentsIndexImport.update({
  path: '/components/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserRoute = UserUserImport.update({
  path: '/user',
  getParentRoute: () => UserRoute,
} as any)

const RestaurateurRestaurateurRoute = RestaurateurRestaurateurImport.update({
  path: '/restaurateur',
  getParentRoute: () => rootRoute,
} as any)

const RestaurateurCreateEditProductRoute =
  RestaurateurCreateEditProductImport.update({
    path: '/create-edit-product',
    getParentRoute: () => rootRoute,
  } as any)

const LoginSignupRoute = LoginSignupImport.update({
  path: '/signup',
  getParentRoute: () => LoginRoute,
} as any)

const LoginLoginRoute = LoginLoginImport.update({
  path: '/login',
  getParentRoute: () => LoginRoute,
} as any)

const DeliveryDeliveryRoute = DeliveryDeliveryImport.update({
  path: '/delivery',
  getParentRoute: () => DeliveryRoute,
} as any)

const DeliveryDeliveriesHistoryRoute = DeliveryDeliveriesHistoryImport.update({
  path: '/deliveries-history',
  getParentRoute: () => DeliveryRoute,
} as any)

const DeliveryDeliveriesRoute = DeliveryDeliveriesImport.update({
  path: '/deliveries',
  getParentRoute: () => DeliveryRoute,
} as any)

const UserRestaurantIdRoute = UserRestaurantIdImport.update({
  path: '/restaurant/$id',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_delivery': {
      id: '/_delivery'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DeliveryImport
      parentRoute: typeof rootRoute
    }
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_restaurant': {
      id: '/_restaurant'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RestaurantImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/_delivery/deliveries': {
      id: '/_delivery/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveryDeliveriesImport
      parentRoute: typeof DeliveryImport
    }
    '/_delivery/deliveries-history': {
      id: '/_delivery/deliveries-history'
      path: '/deliveries-history'
      fullPath: '/deliveries-history'
      preLoaderRoute: typeof DeliveryDeliveriesHistoryImport
      parentRoute: typeof DeliveryImport
    }
    '/_delivery/delivery': {
      id: '/_delivery/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryDeliveryImport
      parentRoute: typeof DeliveryImport
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginImport
      parentRoute: typeof LoginImport
    }
    '/_login/signup': {
      id: '/_login/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LoginSignupImport
      parentRoute: typeof LoginImport
    }
    '/_restaurateur/create-edit-product': {
      id: '/_restaurateur/create-edit-product'
      path: '/create-edit-product'
      fullPath: '/create-edit-product'
      preLoaderRoute: typeof RestaurateurCreateEditProductImport
      parentRoute: typeof rootRoute
    }
    '/_restaurateur/restaurateur': {
      id: '/_restaurateur/restaurateur'
      path: '/restaurateur'
      fullPath: '/restaurateur'
      preLoaderRoute: typeof RestaurateurRestaurateurImport
      parentRoute: typeof rootRoute
    }
    '/_user/user': {
      id: '/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserUserImport
      parentRoute: typeof UserImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_user/restaurant/$id': {
      id: '/_user/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof UserRestaurantIdImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DeliveryRoute: DeliveryRoute.addChildren({
    DeliveryDeliveriesRoute,
    DeliveryDeliveriesHistoryRoute,
    DeliveryDeliveryRoute,
  }),
  LoginRoute: LoginRoute.addChildren({ LoginLoginRoute, LoginSignupRoute }),
  UserRoute: UserRoute.addChildren({ UserUserRoute, UserRestaurantIdRoute }),
  RestaurateurCreateEditProductRoute,
  RestaurateurRestaurateurRoute,
  ComponentsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_delivery",
        "/_login",
        "/_restaurant",
        "/_user",
        "/_restaurateur/create-edit-product",
        "/_restaurateur/restaurateur",
        "/components/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_delivery": {
      "filePath": "_delivery.tsx",
      "children": [
        "/_delivery/deliveries",
        "/_delivery/deliveries-history",
        "/_delivery/delivery"
      ]
    },
    "/_login": {
      "filePath": "_login.tsx",
      "children": [
        "/_login/login",
        "/_login/signup"
      ]
    },
    "/_restaurant": {
      "filePath": "_restaurant.tsx"
    },
    "/_user": {
      "filePath": "_user.tsx",
      "children": [
        "/_user/user",
        "/_user/restaurant/$id"
      ]
    },
    "/_delivery/deliveries": {
      "filePath": "_delivery/deliveries.tsx",
      "parent": "/_delivery"
    },
    "/_delivery/deliveries-history": {
      "filePath": "_delivery/deliveries-history.tsx",
      "parent": "/_delivery"
    },
    "/_delivery/delivery": {
      "filePath": "_delivery/delivery.tsx",
      "parent": "/_delivery"
    },
    "/_login/login": {
      "filePath": "_login/login.tsx",
      "parent": "/_login"
    },
    "/_login/signup": {
      "filePath": "_login/signup.tsx",
      "parent": "/_login"
    },
    "/_restaurateur/create-edit-product": {
      "filePath": "_restaurateur/create-edit-product.tsx"
    },
    "/_restaurateur/restaurateur": {
      "filePath": "_restaurateur/restaurateur.tsx"
    },
    "/_user/user": {
      "filePath": "_user/user.tsx",
      "parent": "/_user"
    },
    "/components/": {
      "filePath": "components/index.tsx"
    },
    "/_user/restaurant/$id": {
      "filePath": "_user/restaurant.$id.tsx",
      "parent": "/_user"
    }
  }
}
ROUTE_MANIFEST_END */
